# Generated by Django 2.1.4 on 2020-04-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('notes_picking', models.TextField(blank=True)),
                ('notes_putaway', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('three_in_row', models.BooleanField()),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='warehouse.Packaging')),
            ],
        ),
    ]
