# Generated by Django 2.1.4 on 2020-04-15 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packaging',
            old_name='height',
            new_name='length',
        ),
    ]
