# Generated by Django 2.1.4 on 2020-04-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200415_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
    ]
