# Generated by Django 2.1.4 on 2020-04-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20200420_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='compartment',
        ),
        migrations.RemoveField(
            model_name='row',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='row',
            name='product',
        ),
        migrations.RemoveField(
            model_name='row',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
