# Generated by Django 2.1.4 on 2020-04-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_product_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='warehouse.Packaging'),
            preserve_default=False,
        ),
    ]
