# Generated by Django 2.1.4 on 2020-04-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='compartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='warehouse.Compartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='row',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='warehouse.Product'),
            preserve_default=False,
        ),
    ]
