# Generated by Django 2.1.4 on 2020-04-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_product_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes_picking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes_putaway',
            field=models.TextField(blank=True, null=True),
        ),
    ]
