# Generated by Django 2.1.4 on 2020-04-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20200420_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Packaging'),
        ),
        migrations.AlterField(
            model_name='row',
            name='compartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Compartment'),
        ),
        migrations.AlterField(
            model_name='row',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Product'),
        ),
        migrations.AlterField(
            model_name='row',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='stock_positions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='symbuilding',
            name='symfactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Symfactory'),
        ),
    ]
