# Generated by Django 2.1.4 on 2020-04-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200415_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.Packaging'),
        ),
    ]
