# Generated by Django 2.1.4 on 2020-04-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200420_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='number_stock_positions',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
