# Generated by Django 2.1.4 on 2020-04-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
    ]
