# Generated by Django 2.1.4 on 2020-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default='hallo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='name',
            field=models.CharField(default='hallo2', max_length=50),
            preserve_default=False,
        ),
    ]
