# Generated by Django 2.1.4 on 2020-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_auto_20200421_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
