# Generated by Django 2.1.4 on 2020-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_withdrawal_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
