# Generated by Django 3.0.5 on 2020-04-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_withdrawal_quantiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
