# Generated by Django 3.0.5 on 2020-04-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20200422_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
