# Generated by Django 3.0.5 on 2020-04-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_product_quantity_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row',
            old_name='stock_positions',
            new_name='current_stock_positions',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='number_stock_positions',
            new_name='total_stock_positions',
        ),
    ]
