# Generated by Django 3.0.5 on 2020-04-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_auto_20200422_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Null',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
