# Generated by Django 3.0.5 on 2020-04-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_vehicle_length_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='symbuilding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.Symbuilding'),
            preserve_default=False,
        ),
    ]
