# Generated by Django 3.0.5 on 2020-04-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_withdrawal_symbuilding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='employee',
        ),
    ]
