# Generated by Django 3.0.5 on 2020-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_remove_withdrawal_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_per_storage_space',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_truck_space',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
